version: '3'
services:
    compiler_test:
        environment:
            - NODE_ENV=development
            - NODE_PATH=/app
        build:
            context: .
            dockerfile: Dockerfile.test
        ports:
            - '8000:8000'
        volumes:
            - /app/node_modules
            - .:/app
